version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
          - "@chromatic-com/*"
      fontsource:
        patterns:
          - "@fontsource/*"
          - "@fontsource-variable/*"
