#!/usr/bin/env node
'use strict';

/**
 * build-tokens.js
 *
 * Compiles Candor design tokens from SCSS source into distributable artifacts:
 *   tokens/candor-tokens.css      — full expanded CSS (for readability / CDN)
 *   tokens/candor-tokens.min.css  — minified CSS (for production <link>)
 *   tokens/candor-tokens.json     — structured JSON for Figma / tooling
 *   tokens/candor-article.css     — article prose styles (framework-agnostic)
 *   tokens/candor-article.min.css — minified article prose styles
 *   tokens/candor-syntax.css      — Prism.js syntax highlighting theme
 *   tokens/candor-syntax.min.css  — minified syntax highlighting theme
 *   tokens/candor-blog.css        — post listing and post card styles
 *   tokens/candor-blog.min.css    — minified post listing styles
 *
 * Usage: node scripts/build-tokens.js
 *   or:  npm run build:tokens
 */

const sass = require('sass');
const fs   = require('fs');
const path = require('path');

const ROOT          = path.resolve(__dirname, '..');
const ENTRY         = path.join(ROOT, 'src/design-tokens/index.scss');
const ARTICLE_ENTRY = path.join(ROOT, 'src/app/components/typography/article/article.component.scss');
const SYNTAX_ENTRY  = path.join(ROOT, 'src/design-tokens/syntax.scss');
const BLOG_ENTRY    = path.join(ROOT, 'src/design-tokens/blog.scss');
const OUT_DIR       = path.join(ROOT, 'tokens');

// ── Compile ────────────────────────────────────────────────────────────────

fs.mkdirSync(OUT_DIR, { recursive: true });

const expanded   = sass.compile(ENTRY, { style: 'expanded' });
const compressed = sass.compile(ENTRY, { style: 'compressed' });

const header =
  '/* Candor Design System — design tokens\n' +
  ' * Auto-generated by `npm run build:tokens`. Do not edit directly.\n' +
  ' * Source: src/design-tokens/\n' +
  ' *\n' +
  ' * Usage:\n' +
  ' *   <link rel="stylesheet" href="candor-tokens.css">\n' +
  ' * or import in CSS/SCSS:\n' +
  ' *   @import url("candor-tokens.css");\n' +
  ' */\n';

fs.writeFileSync(path.join(OUT_DIR, 'candor-tokens.css'),     header + expanded.css);
fs.writeFileSync(path.join(OUT_DIR, 'candor-tokens.min.css'), compressed.css);

// ── Parse ──────────────────────────────────────────────────────────────────

/**
 * Find the content inside the first set of braces after `selector`.
 * Handles nested braces correctly (brace-counting).
 */
function findBlock(css, selector) {
  const idx = css.indexOf(selector);
  if (idx === -1) return null;

  const start = css.indexOf('{', idx);
  if (start === -1) return null;

  let depth = 1;
  let pos   = start + 1;

  while (pos < css.length && depth > 0) {
    if      (css[pos] === '{') depth++;
    else if (css[pos] === '}') depth--;
    pos++;
  }

  return css.slice(start + 1, pos - 1);
}

/**
 * Extract all CSS custom properties from a block of CSS text.
 * Returns { '--prop-name': 'value', ... }
 */
function extractProps(block) {
  const props = {};
  const re    = /(--[\w-]+)\s*:\s*([^;]+);/g;
  let m;
  while ((m = re.exec(block)) !== null) {
    props[m[1]] = m[2].trim();
  }
  return props;
}

const css = expanded.css;

// :root — primitives + light-mode semantics + invariant tokens (spacing, type, shape)
const rootBlock  = findBlock(css, ':root');
const rootTokens = extractProps(rootBlock ?? '');

// Dark-mode overrides — [data-theme="dark"] and @media (prefers-color-scheme: dark)
// both apply the same mixin; we use the explicit [data-theme] block for JSON.
// Sass strips quotes from attribute selectors: [data-theme=dark] not [data-theme="dark"]
const darkBlock  = findBlock(css, '[data-theme=dark]');
const darkTokens = extractProps(darkBlock ?? '');

const output = {
  $schema: 'https://candor.design/schemas/tokens/v1',
  $description:
    'Candor design tokens — auto-generated by `npm run build:tokens`. ' +
    '"root" contains primitives and light-mode semantics. ' +
    '"dark" contains dark-mode overrides only.',
  root: rootTokens,
  dark: darkTokens,
};

fs.writeFileSync(
  path.join(OUT_DIR, 'candor-tokens.json'),
  JSON.stringify(output, null, 2) + '\n',
);

// ── Article prose styles ───────────────────────────────────────────────────
//
// article.component.scss uses only CSS custom properties (var(--...)) — no
// SCSS variable dependencies — so it compiles as a standalone stylesheet.
//
// Framework-agnostic usage:
//   1. Link candor-tokens.min.css first (provides all var(--...) values)
//   2. Link candor-article.min.css second
//   3. Wrap post content: <div class="article article--font-reading">...</div>
//      Font variants: article--font-reading (Noto Serif) | article--font-sans (Noto Sans)

const articleExpanded   = sass.compile(ARTICLE_ENTRY, { style: 'expanded' });
const articleCompressed = sass.compile(ARTICLE_ENTRY, { style: 'compressed' });

const articleHeader =
  '/* Candor Design System — article prose styles\n' +
  ' * Auto-generated by `npm run build:tokens`. Do not edit directly.\n' +
  ' * Source: src/app/components/typography/article/article.component.scss\n' +
  ' *\n' +
  ' * Requires candor-tokens.css (or candor-tokens.min.css) to be loaded first.\n' +
  ' *\n' +
  ' * Usage:\n' +
  ' *   <link rel="stylesheet" href="candor-tokens.min.css">\n' +
  ' *   <link rel="stylesheet" href="candor-article.min.css">\n' +
  ' *\n' +
  ' *   <div class="article article--font-reading"><!-- prose content --></div>\n' +
  ' *\n' +
  ' * Font variants:\n' +
  ' *   article--font-reading  Noto Serif — human/AI-authored prose (default)\n' +
  ' *   article--font-sans     Noto Sans  — utility/syndication contexts\n' +
  ' */\n';

fs.writeFileSync(path.join(OUT_DIR, 'candor-article.css'),     articleHeader + articleExpanded.css);
fs.writeFileSync(path.join(OUT_DIR, 'candor-article.min.css'), articleCompressed.css);

// ── Syntax highlighting theme ─────────────────────────────────────────────
//
// Prism.js token color theme targeting the Candor code block background.
// All token colors validated against light-mode navy-800 code bg; dark-mode
// code bg is even darker so contrast improves automatically.

const syntaxExpanded   = sass.compile(SYNTAX_ENTRY, { style: 'expanded' });
const syntaxCompressed = sass.compile(SYNTAX_ENTRY, { style: 'compressed' });

const syntaxHeader =
  '/* Candor Design System — Prism.js syntax highlighting theme\n' +
  ' * Auto-generated by `npm run build:tokens`. Do not edit directly.\n' +
  ' * Source: src/design-tokens/syntax.scss\n' +
  ' *\n' +
  ' * Requires candor-tokens.css (or candor-tokens.min.css) to be loaded first.\n' +
  ' * Works with candor-article.css or standalone.\n' +
  ' *\n' +
  ' * Usage (11ty with @11ty/eleventy-plugin-syntaxhighlight):\n' +
  ' *   <link rel="stylesheet" href="candor-tokens.min.css">\n' +
  ' *   <link rel="stylesheet" href="candor-article.min.css">\n' +
  ' *   <link rel="stylesheet" href="candor-syntax.min.css">\n' +
  ' *\n' +
  ' * Note: Targets Prism.js class output (language-*, .token.*). Shiki users\n' +
  ' * will need a separate theme — Shiki uses inline styles or its own class system.\n' +
  ' */\n';

fs.writeFileSync(path.join(OUT_DIR, 'candor-syntax.css'),     syntaxHeader + syntaxExpanded.css);
fs.writeFileSync(path.join(OUT_DIR, 'candor-syntax.min.css'), syntaxCompressed.css);

// ── Blog post listing styles ──────────────────────────────────────────────
//
// Post card and post list patterns for blog index pages — framework-agnostic.

const blogExpanded   = sass.compile(BLOG_ENTRY, { style: 'expanded' });
const blogCompressed = sass.compile(BLOG_ENTRY, { style: 'compressed' });

const blogHeader =
  '/* Candor Design System — blog post listing styles\n' +
  ' * Auto-generated by `npm run build:tokens`. Do not edit directly.\n' +
  ' * Source: src/design-tokens/blog.scss\n' +
  ' *\n' +
  ' * Requires candor-tokens.css (or candor-tokens.min.css) to be loaded first.\n' +
  ' *\n' +
  ' * Usage:\n' +
  ' *   <link rel="stylesheet" href="candor-tokens.min.css">\n' +
  ' *   <link rel="stylesheet" href="candor-blog.min.css">\n' +
  ' *\n' +
  ' * See source file for full HTML structure and modifier reference.\n' +
  ' */\n';

fs.writeFileSync(path.join(OUT_DIR, 'candor-blog.css'),     blogHeader + blogExpanded.css);
fs.writeFileSync(path.join(OUT_DIR, 'candor-blog.min.css'), blogCompressed.css);

// ── Report ─────────────────────────────────────────────────────────────────

const kbExpanded   = (Buffer.byteLength(expanded.css)   / 1024).toFixed(1);
const kbCompressed = (Buffer.byteLength(compressed.css) / 1024).toFixed(1);
const rootCount    = Object.keys(rootTokens).length;
const darkCount    = Object.keys(darkTokens).length;

const kbArticleExpanded   = (Buffer.byteLength(articleExpanded.css)   / 1024).toFixed(1);
const kbArticleCompressed = (Buffer.byteLength(articleCompressed.css) / 1024).toFixed(1);
const kbSyntaxExpanded    = (Buffer.byteLength(syntaxExpanded.css)    / 1024).toFixed(1);
const kbSyntaxCompressed  = (Buffer.byteLength(syntaxCompressed.css)  / 1024).toFixed(1);

console.log(`tokens/candor-tokens.css      ${kbExpanded} kB`);
console.log(`tokens/candor-tokens.min.css  ${kbCompressed} kB`);
console.log(`tokens/candor-tokens.json     ${rootCount} root tokens, ${darkCount} dark overrides`);
console.log(`tokens/candor-article.css     ${kbArticleExpanded} kB`);
console.log(`tokens/candor-article.min.css ${kbArticleCompressed} kB`);
const kbBlogExpanded   = (Buffer.byteLength(blogExpanded.css)   / 1024).toFixed(1);
const kbBlogCompressed = (Buffer.byteLength(blogCompressed.css) / 1024).toFixed(1);

console.log(`tokens/candor-syntax.css      ${kbSyntaxExpanded} kB`);
console.log(`tokens/candor-syntax.min.css  ${kbSyntaxCompressed} kB`);
console.log(`tokens/candor-blog.css        ${kbBlogExpanded} kB`);
console.log(`tokens/candor-blog.min.css    ${kbBlogCompressed} kB`);
