#!/usr/bin/env node
'use strict';

/**
 * build-tokens.js
 *
 * Compiles Candor design tokens from SCSS source into distributable artifacts:
 *   tokens/candor-tokens.css      — full expanded CSS (for readability / CDN)
 *   tokens/candor-tokens.min.css  — minified CSS (for production <link>)
 *   tokens/candor-tokens.json     — structured JSON for Figma / tooling
 *
 * Usage: node scripts/build-tokens.js
 *   or:  npm run build:tokens
 */

const sass = require('sass');
const fs   = require('fs');
const path = require('path');

const ROOT    = path.resolve(__dirname, '..');
const ENTRY   = path.join(ROOT, 'src/design-tokens/index.scss');
const OUT_DIR = path.join(ROOT, 'tokens');

// ── Compile ────────────────────────────────────────────────────────────────

fs.mkdirSync(OUT_DIR, { recursive: true });

const expanded   = sass.compile(ENTRY, { style: 'expanded' });
const compressed = sass.compile(ENTRY, { style: 'compressed' });

const header =
  '/* Candor Design System — design tokens\n' +
  ' * Auto-generated by `npm run build:tokens`. Do not edit directly.\n' +
  ' * Source: src/design-tokens/\n' +
  ' *\n' +
  ' * Usage:\n' +
  ' *   <link rel="stylesheet" href="candor-tokens.css">\n' +
  ' * or import in CSS/SCSS:\n' +
  ' *   @import url("candor-tokens.css");\n' +
  ' */\n';

fs.writeFileSync(path.join(OUT_DIR, 'candor-tokens.css'),     header + expanded.css);
fs.writeFileSync(path.join(OUT_DIR, 'candor-tokens.min.css'), compressed.css);

// ── Optional font convenience stylesheet (#169) ──────────────────────────────
// candor-tokens.css only *names* the font families; it doesn't load them. A
// consumer who forgets the Fontsource imports gets a silent fallback (Georgia /
// system-ui). This optional stylesheet does the @imports for them — one opt-in
// line. The Fontsource packages are already runtime deps of this package, so
// they resolve from node_modules in any bundler (Vite/webpack) context.
//
// The import list mirrors src/styles.scss exactly, so consumers load the same
// faces the design system was validated against. Keep the two in sync.
const fontsCss =
  '/* Candor Design System — font convenience imports\n' +
  ' * Auto-generated by `npm run build:tokens`. Do not edit directly.\n' +
  ' *\n' +
  ' * Optional. candor-tokens.css names the font families but does not load them;\n' +
  ' * import this file to pull the actual faces (else text falls back silently).\n' +
  ' * Requires a bundler that resolves bare node_modules specifiers in CSS @import\n' +
  ' * (Vite, webpack, etc.) — the Fontsource packages are deps of this package.\n' +
  ' *\n' +
  ' * Usage (import before candor-tokens.css):\n' +
  ' *   @import "@candor-design/tokens/candor-fonts.css";\n' +
  ' *   @import "@candor-design/tokens/candor-tokens.css";\n' +
  ' */\n' +
  "@import '@fontsource-variable/roboto-flex';\n" +
  "@import '@fontsource-variable/roboto-mono';\n" +
  "@import '@fontsource-variable/noto-sans';\n" +
  "@import '@fontsource-variable/noto-serif';\n" +
  "@import '@fontsource/atkinson-hyperlegible/400.css';\n" +
  "@import '@fontsource/atkinson-hyperlegible/700.css';\n";

fs.writeFileSync(path.join(OUT_DIR, 'candor-fonts.css'), fontsCss);

// ── Parse ──────────────────────────────────────────────────────────────────

/**
 * Find the content inside the first set of braces after `selector`.
 * Handles nested braces correctly (brace-counting).
 */
function findBlock(css, selector) {
  const idx = css.indexOf(selector);
  if (idx === -1) return null;

  const start = css.indexOf('{', idx);
  if (start === -1) return null;

  let depth = 1;
  let pos   = start + 1;

  while (pos < css.length && depth > 0) {
    if      (css[pos] === '{') depth++;
    else if (css[pos] === '}') depth--;
    pos++;
  }

  return css.slice(start + 1, pos - 1);
}

/**
 * Extract all CSS custom properties from a block of CSS text.
 * Returns { '--prop-name': 'value', ... }
 */
function extractProps(block) {
  const props = {};
  const re    = /(--[\w-]+)\s*:\s*([^;]+);/g;
  let m;
  while ((m = re.exec(block)) !== null) {
    props[m[1]] = m[2].trim();
  }
  return props;
}

const css = expanded.css;

// :root — primitives + light-mode semantics + invariant tokens (spacing, type, shape)
const rootBlock  = findBlock(css, ':root');
const rootTokens = extractProps(rootBlock ?? '');

// Dark-mode overrides — [data-theme="dark"] and @media (prefers-color-scheme: dark)
// both apply the same mixin; we use the explicit [data-theme] block for JSON.
// Sass strips quotes from attribute selectors: [data-theme=dark] not [data-theme="dark"]
const darkBlock  = findBlock(css, '[data-theme=dark]');
const darkTokens = extractProps(darkBlock ?? '');

const output = {
  $schema: 'https://candor.design/schemas/tokens/v1',
  $description:
    'Candor design tokens — auto-generated by `npm run build:tokens`. ' +
    '"root" contains primitives and light-mode semantics. ' +
    '"dark" contains dark-mode overrides only.',
  root: rootTokens,
  dark: darkTokens,
};

fs.writeFileSync(
  path.join(OUT_DIR, 'candor-tokens.json'),
  JSON.stringify(output, null, 2) + '\n',
);

// ── Report ─────────────────────────────────────────────────────────────────

const kbExpanded   = (Buffer.byteLength(expanded.css)   / 1024).toFixed(1);
const kbCompressed = (Buffer.byteLength(compressed.css) / 1024).toFixed(1);
const rootCount    = Object.keys(rootTokens).length;
const darkCount    = Object.keys(darkTokens).length;

console.log(`tokens/candor-tokens.css      ${kbExpanded} kB`);
console.log(`tokens/candor-tokens.min.css  ${kbCompressed} kB`);
console.log(`tokens/candor-tokens.json     ${rootCount} root tokens, ${darkCount} dark overrides`);
console.log(`tokens/candor-fonts.css       6 @font imports`);
