name: Publish

on:
  release:
    types: [published]

jobs:
  publish-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - run: npx npm@latest install -g npm
      - run: npm ci
      - run: npm run build:tokens
      - run: npm publish --access public --provenance

  publish-web-components:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - run: npx npm@latest install -g npm
      - run: npm ci
      - run: npm run build:wc
      - run: npm publish --access public --provenance
        working-directory: web-components
